package game.territory.building;

public enum BuildingModifierType {
	ADD_TAX_INCOME_BASE, ADD_TAX_INCOME_MULT,
	ADD_LEVY_LIMIT_BASE, ADD_LEVY_LIMIT_MULT,
	ADD_POPULAR_OPINION,
	ADD_DEVELOPMENT_TARGET, ADD_DEVELOPMENT_PACE,
	ADD_TRANSPORT_CAPACTIY,
	ADD_FOOD_PRODUCTION, ADD_FOOD_STORAGE,
	ADD_ECONOMY_GROTH_TARGET,
	ADD_RULER_PRESTIGE, ADD_RULER_PIETY,
	ADD_FORTIFICATION
}
