package game.trait;

public enum CharacterModifierType {

	ADD_PROWESS, ADD_LEARNING, ADD_DIPLOMACY, ADD_MARTIAL, ADD_INTRIGUE, ADD_STEWARDSHIP,

	MULT_TROOP_SUPPLY, MULT_TROOP_SPEED, ADD_TROOP_MORALE, MULT_TROOP_SIZE,

	MULT_BUILDING_CONSTRUCTION_SPEED, MULT_BUILDING_CONSTRUCTION_COST, MULT_BUILDING_MAINTANANCE_SPEED,
	MULT_BUILDING_MAINTANANCE_COST,

	AI_ZEAL, AI_AGGRO, AI_COMPASSION, AI_CONFIDENCE,
	
	

}
