package game.trait;

public enum OpinionType {

	GENERAL, POPULANCE, COMMONER, HEAD_OF_STATE, RULER, SAME_FAITH, OTHER_FAITH, SAME_CULTURE, OTHER_CULTURE,
	ATTRACTION, ARISTOCRACY, TYRANN, DICTATOR, VASSAL_OPINION, SAME_TRAIT_OPINION, OPPOSITE_TRAIT_OPINION

}
